### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Kaljurand/K6nele#116]
I've updated to Java17 but: https://gitlab.com/fdroid/fdroiddata/-/jobs/6342586293#L391

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/5909cb0bdb3a5211f4f31d16e3e0a7385d1116df

**Comment by Kaljurand** [comment]
Hopefully fixed by just removing the dependency on ``BuildConfig``.

**Comment by licaon-kter** [comment]
Now it's a different error: [ee.ioc.phon.android.speak_1916.log.gz](https://github.com/Kaljurand/K6nele/files/14557278/ee.ioc.phon.android.speak_1916.log.gz)

**Comment by Kaljurand** [comment]
The ee.ioc.phon.android.speak_1916.log.gz URL does not resolve for me.

**Comment by licaon-kter** [comment]
Odd, will reattach asap

**Comment by licaon-kter** [comment]
[ee.ioc.phon.android.speak_1916.log.gz](https://github.com/Kaljurand/K6nele/files/14585768/ee.ioc.phon.android.speak_1916.log.gz)

this works now, does for you too?

**Comment by Kaljurand** [comment]
Thanks! I could download the error log now. Some of these errors seem familiar to me as lint warnings. It would take a while to work-around all of them, though...

One thing to try in the F-Droid build is to use my exact ``gradle.properties`` (https://github.com/Kaljurand/K6nele/blob/v1.9.16/gradle.properties):

```
android.defaults.buildfeatures.buildconfig=true
android.enableJetifier=false
android.nonFinalResIds=false
android.nonTransitiveRClass=false
android.useAndroidX=true
org.gradle.jvmargs=-Xmx2560m
org.gradle.unsafe.configuration-cache=true
```

or some subset of it, e.g.

```
android.nonFinalResIds=false
android.nonTransitiveRClass=false
```

seem related (https://stackoverflow.com/questions/76334499/error-constant-expression-required-android-studio).

**Comment by Kaljurand** [comment]
Maybe I'm misunderstanding how the F-Droid build works, but this line there:

```
prebuild: echo "android.useAndroidX=true" > ../gradle.properties
```

seems to overwrite the existing ``gradle.properties`` with a single property assignment.

**Comment by licaon-kter** [comment]
Indeed, that was used in past recipes, but now it was at fault

thanks https://gitlab.com/fdroid/fdroiddata/-/commit/02ea288aae152ec78e1e341b3c5993a761f435c4
