### ISSUE TITLE
Add Spanish lang???

### ISSUE THREAD

**Issue by wuniversales** [Kaljurand/K6nele#117]
I can't find the way to add languages to the application, maybe it is not implemented?
Thanks

**Comment by Kaljurand** [comment]
You can install a new recognizer service that supports Spanish (as a separate Android app). Kõnele will then pick it up automatically, i.e. show it in the list of available recognizers. See the answer to a similar question: https://github.com/Kaljurand/K6nele/discussions/38 or e.g. use Whisper as done in https://github.com/Kaljurand/K6nele/discussions/103.

There are plans to improve the UI to support multiple services/languages better (https://github.com/Kaljurand/K6nele/issues/113),  but it won't involve discovering and downloading "language packs", but just using the services already installed at the general Android level.
