### ISSUE TITLE
Build net-speech-api from source

### ISSUE THREAD

**Issue by krt16s** [Kaljurand/K6nele#37]
Jar files are binaries that shouldn't be inside the repository. Could you wire it up to build from the souce code (e.g. using submodules) or push net-speech-api to mavenCentral?

**Comment by Kaljurand** [comment]
net-speech-api is now built from the submodule. Installation instructions were updated in the README to be:

    git clone --recursive git@github.com:Kaljurand/K6nele.git
    cd K6nele
    gradle -b other.gradle makeNetSpeechApi
    gradle assembleRelease

This is available in https://github.com/Kaljurand/K6nele/releases/tag/v1.2.06.

**Comment by krt16s** [comment]
See 4797003c4cdbd443bbff74bd60ae1952a495e675 and aeb74dd11a827d3a1a08246a8c9ac783e377a94c.
