### ISSUE TITLE
No transcription found error

### ISSUE THREAD

**Issue by mrts** [Kaljurand/K6nele#48]
Many thanks for the application, it helps me a lot!

I have been using it heavily for a couple of months. Unfortunately now it stopped working and responds with _no transcription found_ error when I speak. How can I fix this?

**Comment by alumae** [comment]
Can you try again? It's possible that it was caused by a problem in the server.

**Comment by mrts** [comment]
Works like a charm again, thanks a lot ☺️ !

**Comment by mrts** [comment]
Same problem again...

**Comment by alumae** [comment]
It works for me.

**Comment by mrts** [comment]
Works for me now again, too. Maybe error handling could be improved so that it would be easier for the users to understand the causes of errors: their own connectivity issues, app issues, server issues. Closing again, thanks once more for the absolutely great service 🙂 👍!
