### ISSUE TITLE
Could not find method google() for arguments [] on repository container

### ISSUE THREAD

**Issue by mariasmo** [Kaljurand/K6nele#49]
hi,

i am getting the above error. Could you please tell what is wrong?
 thanks

additional info:

username$ gradle assemble --info
 
Starting Build
Settings evaluated using settings file '/Applications/Dev/AS/Samples/K6nele/settings.gradle'.
Projects loaded. Root project using build file '/Applications/Dev/AS/Samples/K6nele/build.gradle'.
Included projects: [root project 'K6nele', project ':app', project ':net-speech-api', project ':speechutils', project ':speechutils:app']
Evaluating root project 'K6nele' using build file '/Applications/Dev/AS/Samples/K6nele/build.gradle'.

FAILURE: Build failed with an exception.

* Where:
Build file '/Applications/Dev/AS/Samples/K6nele/build.gradle' line: 3

* What went wrong:
A problem occurred evaluating root project 'K6nele'.
> Could not find method google() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

**Comment by Kaljurand** [comment]
There were some png-resources missing which made the build fail. I've added these in https://github.com/Kaljurand/K6nele/commit/f51b66087f8b8ec1a48100a7bfe58d461cf4df8f

However, your issue seems to be caused by something else, but I cannot reproduce it, e.g. this sequence of commands works fine for me, resulting in an APK in `app/build/outputs/apk/debug/`.

```
git clone --recursive git@github.com:Kaljurand/K6nele.git
cd K6nele/
gradle assembleDebug
```

I'm using this platform to build:

```
$ gradle -v

------------------------------------------------------------
Gradle 4.1
------------------------------------------------------------

Build time:   2017-08-07 14:38:48 UTC
Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Linux 4.4.0-101-generic amd64
```

Have you tried googling for the error message that you are getting and applying the possible solutions?

**Comment by mariasmo** [comment]
Hi kaljurand,
thanku for ur prompt response. really appreciate it. my gradle version is 2.1. i did google for this error and most people suggest i upgrade my gradle version.i am trying it now.i will upgrade my gradle version and see if it works.will update

**Comment by mariasmo** [comment]
hi kaljurand,

after upgrading the gradle version to 4.3 i am past that error. but i am now stuck with the following error.

any help?

thanks

=========================

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileReleaseJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
   > Could not resolve project :speechutils:app.
     Required by:
         project :app
      > Unable to find a matching configuration of project :speechutils:app: None of the consumable configurations have attributes.
   > Could not resolve project :net-speech-api.
     Required by:
         project :app
      > Unable to find a matching configuration of project :net-speech-api: None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

**Comment by Kaljurand** [comment]
It seems that the submodules (speechutils and net-speech-api) are not cloned, i.e. the respective subdirectories do not exist or do not contain any files. This does not happen if one is authenticated. I need to investigate how to best clone the repo with submodules without authentication and/or as read-only.

**Comment by mariasmo** [comment]
hi kaljurand

u r right. the submodules are empty. but i am not sure if it's an authentication issue. looks like the speechutils and net-speech-api are in their own repos. could that be an issue? i trie manually downloading the repo as a zip file. that has the same issue as well. it creates the two directories but they are empty.

any suggestions?

thanks

**Comment by mariasmo** [comment]
hi kaljurand

so i got bot the above mentioned repos separately and put them in the K6nele repo and build it. it built successfully.

now how to play with it? any instructions? what exactly does it do? do i need to have the gstream-server set up first?

please let me know.

thanks

**Comment by Kaljurand** [comment]
There is documentation at http://kaljurand.github.io/K6nele/about/ (most of it in Estonian though) and https://github.com/Kaljurand/K6nele/tree/master/docs. The app works out of the box with Estonian speech recognition. If you want to use it with your own recognizer then you need to set up your own server. (In case you encounter a problem, please open a separate issue.)
