### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by mariasmo** [Kaljurand/K6nele#50]
Hi kaljurand,

(i put this question on alumae github page as well. i thought may be you can answer these questions.thankyou) 

i am new to kaldi and the gstreamer plugin.

I have a question though. what is the reason behind choosing gstreamer to pass the audio to kaldi for decoding?

could a simple server be sufficient to pass the audio to kaldi for decoding? are there any limitations to such an approach that made you choose the gstreamer to act as an intermediary(pardon my ignorance if my thought process is wrong)?

thanks in advance

**Comment by alumae** [comment]
Answered it at https://github.com/alumae/kaldi-gstreamer-server/issues/102

**Comment by Kaljurand** [comment]
Closing as not related to Kõnele
