### ISSUE TITLE
How to set Notes or another application to use Kaldi and not Google ASR?

### ISSUE THREAD

**Issue by alerenato** [Kaljurand/K6nele#53]
Hi Kaarel Kaljurand,
I'm testing the library and I'm excited about the features it has. In one of the tests, I used an Android tablet setting the language to Estonian and the automatic recognition to Kaldi, while the web socket pointed to my local server where Kaldi runs with Spanish models. K6nele recognized it as expected, but when I use an application such as Notes or Handoff the system uses Google models in Spanish, even though it is set in Estonian (fast recognition). I disabled "Google OK" but still using the Google model. How can I use other applications with Kaldi? Thanks in advance.

**Comment by alerenato** [comment]
Excuse me. I had not read well the part of changing the input method: keyboard by K6nele. Now is working it as expected.

**Comment by Kaljurand** [comment]
I'm glad that you found a solution.
