### ISSUE TITLE
emulator android studio

### ISSUE THREAD

**Issue by samarbac** [Kaljurand/K6nele#59]
Hello :)
help me please :( when running the android application, the emulator (Nexus 5x api 28-2) remains in this state.
is there a solution ???????
thank you
![38217183_2085399355062132_7612757685947072512_n](https://user-images.githubusercontent.com/17397388/43552885-bf4e8294-95ec-11e8-953b-d3038a0f8e1b.png)

**Comment by Kaljurand** [comment]
Closing, because this issue does not seem to be related to Kõnele. If it actually is then post a screenshot that has Kõnele on it, and reopen.
