### ISSUE TITLE
Audio Support in English and Setting Default Language English

### ISSUE THREAD

**Issue by sheminnyoka** [Kaljurand/K6nele#67]

**Comment by sheminnyoka** [comment]
Currently the audio supported in language i think estonian in extras Demo , In my project i need play audio in english language.also need default lang as english . Could you please help.

**Comment by Kaljurand** [comment]
Are you talking about the text-to-speech language, i.e. the language in which the voice prompt (that is set using ee.ioc.phon.android.extra.VOICE_PROMPT) is spoken? This can be set using RecognizerIntent.EXTRA_LANGUAGE. It seems that the Extras demo does not set this extra, so the prompt is spoken in whatever language the default text-to-speech engine is using as the default.

If you are talking about speech-to-text then the input language is decided by the default service that you have selected for the "Voice search panel". If you haven't selected anything then "Kõnele (fast recognition)" is used, which by default uses the Estonian server. You can implement your own English service and use that in Kõnele.

**Comment by sheminnyoka** [comment]
in text  to speech, if i am telling how rare you  , it will display text corresponding estionian sentence , i have given changes like RECOGNIZERINTENTR.EXTRA_lang but did nt getting , but not display as how r u

Secondly , did u have any english service which can be used in konele lib re using it in my app ,please

In my app default when app is using , like extrasdemo .instead of estonian text from speech to text , need english Could you please help to provide english service which can use here

**Comment by Kaljurand** [comment]
It seems that you are talking about "speech-to-text", not "text-to-speech". I assume that you are using the "fast service". This service calls a cloud server and passes to it the value of EXTRA_LANGUAGE. However, the default cloud server (probably) ignores this info and always returns an Estonian recognition. The server is not developed as part of the Kõnele project: Kõnele is just a front-end. I'm not aware of a public English server, but you could try to set up your own based on https://github.com/jcsilva/docker-kaldi-gstreamer-server.
