### ISSUE TITLE
Offline Speech Recognition

### ISSUE THREAD

**Issue by sheminnyoka** [Kaljurand/K6nele#68]
Here in this library , can we implement speech recognition when offline , Can you provide any solution here or anyother way.Is Functionality Implemented in Konele.

**Comment by Kaljurand** [comment]
The 2 services included with Kõnele use a cloud server, i.e. you need to be online. However, you can use Kõnele as a front-end to any service that implements Android's SpeechRecognizer API (https://developer.android.com/reference/android/speech/SpeechRecognizer), incl. offline services. Other than that there is no special support for offline speech recognition.
