### ISSUE TITLE
How difficult it would be to add offline speech recognition backend

### ISSUE THREAD

**Issue by andreytkachenko** [Kaljurand/K6nele#78]
It would be great if anyone give me the brief introduction of the structure of the project and what will I need to create/change to add [vosk-api](https://github.com/alphacep/vosk-api) backend with Russian and English models. I am a Rust developer and have no experience in android development. Thank You.

**Comment by Kaljurand** [comment]
From the Kõnele perspective it would be best if you implemented a separate app that wraps the vosk-api into an implementation of Android's RecognitionService (https://developer.android.com/reference/android/speech/RecognitionService). Once this app is installed on the device, Kõnele will be able to list it as one of the available services and the Kõnele user can select it as one of its default services. Here are some examples of RecognitionService implementations:

- https://github.com/Kaljurand/speechdemo1 (just a demo but shows the basic structure of such an app)
- https://github.com/Kaljurand/speech-trigger (offline service based on PocketSphinx, I never got it to fully work though)
- https://github.com/Kaljurand/K6nele-service (service that uses an online server for the recognition; the same code is also part of Kõnele itself, it was mainly split off into a separate app just to debug some Android 11 issues)

So you could fork one of the above projects and try to inject the vosk-api java code (or its Android demo) into this fork. I have no experience with Vosk, so cannot help further with that.

**Comment by andreytkachenko** [comment]
Great explanation! Thank you.
