### ISSUE TITLE
android 11 insufficient permissions

### ISSUE THREAD

**Issue by jim-perkins** [Kaljurand/K6nele#82]
Hi
I am using this app  v1.7.40 downloaded from fdroid with my own personal kaldi-gstreamer-server.  It worked fine on android 10.  with android 11 the app does not ask for any permissions.   Even after manually granting permissions I get this error. Insufficient permissions.

https://github.com/Kaljurand/K6nele/blob/f4783aa0572d9cf380eff06cd9620b74eaff71ec/app/src/main/res/values/strings.xml#L224

the device is a pixel 3xl.  I tested this with the latest official google firmware and also with grapheneOS ( which does not utilize google play services ) 

 thanks so much for this app it gives me the ability to use  Speech to text without using google servers.
Let me know how I can help

**Comment by Kaljurand** [comment]
You are probably encountering the issue described in https://issuetracker.google.com/issues/160395361.
I believe that it's a regression in Android 11, but Google seems to disagree (although I'm not sure they carefully read the bug report). In any case, I don't know how to work around this issue within Kõnele itself.

The current solution is to install the server interface as a separate app (e.g. https://github.com/Kaljurand/K6nele-service) and set Kõnele to use that as the recognition provider. This setup is demonstrated in the video https://www.youtube.com/watch?v=VLjV8JulEow (in Estonian).

It's best to use Kõnele v1.7.50 and Kõnele service v0.1.00, available on the Releases pages, although slightly earlier versions should also work.

Kõnele service is currently not available on F-Droid, but as it's more-or-less a subset of Kõnele it could be submitted there as well.

**Comment by jim-perkins** [comment]
thanks for the quick reply.  I can confirm that installing Release versions of the K6nele-service and K6nele resolved the permissions issues with Android 11.  Specifically GrapheneOS based on Android 11.

Regarding submitting K6nele-service to fdroid:  It isnt a problem installing the service from the release page however I use fdroid to update my FOSS apps.  Probably wont update K6nele service again till it quits working :-)   I imagine as android 11 becomes mainstream this issue will become more prevalent, although I admit I didnt read the issue on google because it required a google account login.    

thanks again for your time and effort on this app and support. I will let you decide whether to close this issue or not,

**Comment by Kaljurand** [comment]
Glad that you managed to resolve the issue.

Here is a copy of the above-mentioned bug report (https://issuetracker.google.com/issues/160395361), titled
**[Android 11 DP/Beta] ee.ioc.phon.android.speak fails to access SpeechRecognizer due to lack of permission** 

2020-07-03. Me:

> The app Kõnele (ee.ioc.phon.android.speak) works on Android 10, but does not work on Android 11.
> I am an Android developer, using build RPB1.200504.020 on Pixel 2.
> 
> In order to reproduce the problem:
> 
> 1. Install the app (beta version 1.7.30, or the latest stable version 1.6.98)
> 2. Launch the app
> 3. Press on the yellow microphone button
> 
> Expected: a permission requesting dialog should pop up, asking for the microphone permission
> 
> Actual: the microphone button turns grey and nothing happens.
> 
> When the microphone permission is first assigned via the system dialog ("App info") and then the microphone button is pressed, then a short message briefly appears: "[insufficient permissions]". Expected: the app should start recording (because the permissions have been given).
> 
> Some background.
> When the microphone button is pressed then Kõnele requests a speech recognizer service via the SpeechRecognizer API (https://developer.android.com/reference/android/speech/SpeechRecognizer). It can request any existing service installed on the phone, but it also comes with two services of its own, one of them is requested by default. The described issue does not occur when accessing Google's recognizer services. But it does occur when accessing the Kõnele's own service. (The requested service can be specified in the Kõnele settings.)
> 
> So I think there is a regression in the SpeechRecognizer API.

2020-07-10. Google:

> This is a issue that the app developer needs to fix. The app assumes once a permission is granted it is always granted. That is not the case. The user might revoke it.
> App developer should follow the [official guide on requesting permissions](https://developer.android.com/training/permissions/requesting). This is designed to prevent situations like this.

2020-07-31. Me:

> Please reconsider the resolution of this issue. I would like to point out that:
> 
> - an app (specifically ee.ioc.phon.android.speak) that works fine in Android 10 and earlier, does not work anymore on Android 11 (regardless of if it targets v11 or an earlier version). Is this breaking of backwards compatibility really an intended behavior?
> 
> - if the microphone permission has been explicitly granted (e.g. via the system UI, i.e. App info / Permissions) and has NOT been revoked, the recording still fails because of lack of permissions.
> 
> Meanwhile I've found that there is no issue if the SpeechRecognizer service implementation is called from a separate app. So a work-around has been to move this implementation from ee.ioc.phon.android.speak into a new app (https://github.com/Kaljurand/K6nele-service; ee.ioc.phon.android.k6neleservice). However, while this approach has some benefits (more modularity), it has also some major downsides (the user has to install 2 apps, and grant the microphone permissions for them separately).

**Comment by felixwiemuth** [comment]
Hi, I just had the same issue when trying out the app (didn't try the workaround though). Could you mention the limitation and add a link to this issue/workaround in the F-Droid description as well as when starting the app on Android 11?

Adding the service app to F-Droid as well would then make sense of course.

Thanks for bringing Open source / service-independent speech recognition to Android!

**Comment by Kaljurand** [comment]
Yes, there are 3 TODO-items here:

- improve the F-Droid description. The link to "Kõnele service" is already in the description (https://github.com/Kaljurand/K6nele/blob/master/metadata/en-US/full_description.txt), but for some reason the description is only shown in the F-Droid app (and the link is not rendered), while the F-Droid website contains some old/obsolete description
- publish "Kõnele service" on F-Droid
- implement a wizard that runs during the first launch and helps the user set up and configure the dependencies

I'll look into the first two items in the coming weeks. The third item is more work.

**Comment by felixwiemuth** [comment]
> * improve the F-Droid description. The link to "Kõnele service" is already in the description (https://github.com/Kaljurand/K6nele/blob/master/metadata/en-US/full_description.txt), but for some reason the description is only shown in the F-Droid app (and the link is not rendered), while the F-Droid website contains some old/obsolete description

Probably F-Droid doesn't support the `<a href>` tag for descriptions in the app (it seems it does on the website). In the app, a plain URL in the description is rendered as a link. Not sure about the F-Droid website in that case. There is an [example](https://github.com/Kunzisoft/KeePassDX/blob/123288e745177410e2cfaa97332416e26fe458e7/fastlane/metadata/android/en-US/full_description.txt) where the URL is used as link target and text in `<a href>`, so that should work in both places.

Maybe you also have to remove the description from the [metadata repository](https://gitlab.com/fdroid/fdroiddata/-/blob/0a0537ff5013a2210fe5ad810f63d66b2c0ec78b/metadata/ee.ioc.phon.android.speak.yml) so that the one from your metadata folder is used.

> * implement a wizard that runs during the first launch and helps the user set up and configure the dependencies
> 
Maybe instead of a wizard, for the beginning a dialog with the link in case a dependency is missing (on Android 11) is all that is needed :).

**Comment by Kaljurand** [comment]
Thanks @felixwiemuth ! Regarding the description I've made an attempt to improve the situation:

- https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8827
- https://github.com/Kaljurand/K6nele/commit/5db75c7966e12a1baa3db3767772677319f229a1

**Comment by ippocratis** [comment]
Android 13 has this bug
Can someone reopen?
