### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [Kaljurand/K6nele#86]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by Kaljurand** [comment]
The screenshot(s) and the changelog now show up in https://f-droid.org/packages/ee.ioc.phon.android.speak/ and in the F-Droid app. (The updated short/full descriptions still do not, but this is maybe a separate issue.)
